version: '3.1'
services:
  db:
    image: 'postgres:12.3-alpine'
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - '5432:5432'
  liquibase:
    image: webdevops/liquibase:postgres
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    restart: 'no'
    depends_on:
      - db
    volumes:
      - ./scripts/:/scripts/
      - ./src/main/resources/liquibase/:/changelog/
    command: /scripts/wait_for_postgres_then_init.sh
  app:
    build: .
    depends_on:
      - db
    ports:
      - '8080:8080'
